### ISSUE TITLE
regression in uri_escape

### ISSUE THREAD

**Issue by dakkar** [libwww-perl/URI#111]
with URI 5.12, I can say `uri_escape($foo,'\W')` and all non-word characters in `$foo` get percent-encoded

with URI 5.13, nothing seems to be percent-encoded

I believe that `\W` is a valid string to pass as 2nd argument, because `/[\W]/` is a valid regex and matches non-word characters.

**Comment by haarg** [comment]
This is caused by 1a4ed66802f26c15cccd66c0b5d489cf9f3e3ba4.

@happy-barney

**Comment by gregoa** [comment]
We (well,  so far only me :)) are also seeing regressions in Debian:

https://bugs.debian.org/1021511
"URI 5.13 breaks Net::Twitter::Lite::WithAPIv1_1 and Net::Twitter"

Cheers,
gregor
