### ISSUE TITLE
Bareword "URI::HAS_RESERVED_SQUARE_BRACKETS" not allowed while "strict subs" in use

### ISSUE THREAD

**Issue by charsbar** [libwww-perl/URI#120]
```
$ perl -E 'eval qq{require "./local/lib/perl5/URI/_generic.pm"} or die $@'
Bareword "URI::HAS_RESERVED_SQUARE_BRACKETS" not allowed while "strict subs" in use at ./local/lib/perl5/URI/_generic.pm line 13.
Compilation failed in require at (eval 1) line 1.
```

**Comment by haarg** [comment]
You are loading `URI::_generic` from a location that isn't in `@INC`, so the `URI.pm` it loads is from a different version. This is not a bug in the module.

**Comment by charsbar** [comment]
Thanks. That makes sense. I got a report from my colleague who encountered this issue by starman -M(several modules). We should add -I local/lib/perl5 so that all the modules are loaded from there.

**Comment by distler** [comment]
Shouldn't it be `$URI::HAS_RESERVED_SQUARE_BRACKETS`, not `URI::HAS_RESERVED_SQUARE_BRACKETS` (twice in `_server.pm` and once in `_generic.pm`)?

At least Perl 5.34 seems to think so.

**Comment by haarg** [comment]
No, `HAS_RESERVED_SQUARE_BRACKETS` is a constant, not a variable.

**Comment by distler** [comment]
Ack! Sorry, my bad.
