### ISSUE TITLE
URI::_generic requires Regexp::IPv6 leads to die (not installed and not trapped)

### ISSUE THREAD

**Issue by jackdeguest** [libwww-perl/URI#122]
On line 25 of [URI::_generic](https://github.com/libwww-perl/URI/blob/master/lib/URI/_generic.pm#L25) there is a call to `require` module [Regexp::IPv6](https://metacpan.org/pod/Regexp::IPv6), which is not a core module and is not installed by default, thus leading the module to die unexpectedly.

At least, this `require` should be eval'ed to trap ensuing fatal error.

**Comment by haarg** [comment]
It is already trapped by an eval.

**Comment by jackdeguest** [comment]
> It is already trapped by an eval.

Yes, my apologies. I must have been using an earlier version.

**Comment by haarg** [comment]
The use of Regexp::IPv6 in this module has always been protected by an eval. You may have problems elsewhere in your code, possibly related to a `__DIE__` hook.
