### ISSUE TITLE
URI 5.22, 5.23 causes HTML::Form tests to fail

### ISSUE THREAD

**Issue by dbcooper** [libwww-perl/URI#135]
When using Perl 5.36.3, trying to build/install HTML::Form (a dependency of WWW::Mechanize) causes tests fail when URI 5.22 or 5.23 is installed.  If URI 5.21 is installed, the tests pass successfully.

I'm not trying to imply your code is wrong, it's just that URI is most recently updated module (AFAICT) in my current mess of dependencies.

Failing tests from `t/form.t` in HTML::Form, v6.11
```
#   Failed test at t/form.t line 94.
#          got: '21'
#     expected: '1'

#   Failed test at t/form.t line 95.
#                   'Use of uninitialized value in string eq at /usr/local/perlbrew/perls/perl-5.36.3/lib/site_perl/5.36.3/URI/_query.pm line 38.
# '
#     doesn't match '(?^:^Unknown input type 'xyzzy')'

#   Failed test at t/form.t line 158.
#          got: '4'
#     expected: '0'

#   Failed test at t/form.t line 274.
#          got: '27'
#     expected: '0'
# Looks like you failed 4 tests of 134.
t/form.t ...............
```

FWIW, I see a lot of the "Use of uninitialized value in string eq at /usr/local/perlbrew/perls/perl-5.36.3/lib/site_perl/5.36.3/URI/_query.pm line ..." type of warnings from other modules I'm building (as well).

I realize this bug report is pretty weak but I wanted to share in case someone else runs into this issue or reporting it is useful.

Thank you.

**Comment by oalders** [comment]
Oof. I reverted the wrong commit earlier today. 😢 I'll fix it now. Thank you so much for opening this ticket!

**Comment by dbcooper** [comment]
> Thank you so much for opening this ticket!

You are welcome!  Thank _you_ for your prompt and kind response.

**Comment by oalders** [comment]
> Thank you for your prompt and kind response.

You're very welcome! I can't release on my current machine for reasons, but I should be able to get a new release out in a couple of hours.

**Comment by oalders** [comment]
New release has been uploaded to PAUSE.
