### ISSUE TITLE
The URI module seems to have disappeared from CPAN

### ISSUE THREAD

**Issue by briandfoy** [libwww-perl/URI#146]
There are no permissions for it on PAUSE: [View Permissions](https://pause.perl.org/pause/authenquery?ACTION=peek_dist_perms&pause99_peek_dist_perms_by=de&pause99_peek_dist_perms_query=URI&pause99_peek_dist_perms_sub=Submit).

MetaCPAN doesn't show it [https://metacpan.org/pod/URI](https://metacpan.org/pod/URI).

`cpan` cannot resolve it because it is not in 02packages.

`cpanm` cannot find it in cpanmetadb but falls back to http://cpan.metacpan.org/authors/id/O/OA/OALDERS/URI-5.29.tar.gz

```
$ cpanm URI
! Finding URI on cpanmetadb failed.
```

**Comment by oalders** [comment]
This is related to https://github.com/libwww-perl/URI/pull/16

The new upload contained some unauthorized modules. They didn't exist on CPAN, so we thought it was correct, but there were previously (now deleted) modules by these names and the author still has permissions. I requested PAUSE delete the latest upload while this gets sorted out. I wasn't able to get the previous module reset to be the "latest", but I can try again.

**Comment by briandfoy** [comment]
It seems weird that the previous version would disappear from 02packages and the module would disappear from the permissions view in PAUSE. I hadn't noticed that when I've uploaded non-indexable modules. Maybe something happened manually.

But things happen.

**Comment by oalders** [comment]
I've requested a re-index of 5.29 from PAUSE as I think a MetaCPAN re-index won't work until that has happened. I haven't bungled things in this particular way before, so this is a new one for me.

**Comment by oalders** [comment]
Also, not sure what 

```
2024/10/18 21:45:46 I release: Downgrading release cvswebedit-v2.0b1
```

is about. 🤔

**Comment by choroba** [comment]
@oalders Probably related to https://metacpan.org/release/MRJC/cvswebedit-screenshots-v2.0b1

**Comment by oalders** [comment]
@choroba, thanks! I see that contained a `URI::Escape`.
