### ISSUE TITLE
Version 5.30 deleted

### ISSUE THREAD

**Issue by eserte** [libwww-perl/URI#147]
The release https://metacpan.org/release/OALDERS/URI-5.30 is marked as deleted and only available on BackPAN --- is this intentional?

**Comment by oalders** [comment]
Yes, I kind of bungled that release. It contained 3 modules which I did not (yet) have permissions on. I got the permissions a few days ago, so I hope to release a new URI shortly.

**Comment by oalders** [comment]
I've just uploaded 5.31, which is the same as 5.30
