### ISSUE TITLE
Bareword found where operator expected at /usr/local/cpanel/Cpanel/URI/Escape/Fast.pm line 19

### ISSUE THREAD

**Issue by B3nihana** [libwww-perl/URI#38]
Got the following error from Cron
Email Subject: /usr/local/bin/perl /usr/local/cpanel/3rdparty/quickinstall/scripts/checkupdates.pl

> Bareword found where operator expected at /usr/local/cpanel/Cpanel/URI/Escape/Fast.pm line 19, near "s/([^A-Za-z0-9\-_\.~])/$escapes{$1}/gr"

**Comment by skaji** [comment]
URI/Escape/Fast.pm is not a part of URI distribution.
