### ISSUE TITLE
Add at least one example to URI::_punycode

### ISSUE THREAD

**Issue by jidanni** [libwww-perl/URI#45]
Please add at least one example to
```
NAME
       URI::_punycode - encodes Unicode string in Punycode

SYNOPSIS
         use URI::_punycode;
         $punycode = encode_punycode($unicode);
         $unicode  = decode_punycode($punycode);
```
else the user cannot tell if it is due to improper input that he gets e.g.,
```
Use of uninitialized value $input in split at /usr/share/perl5/URI/_punycode.pm line 96.
```

**Comment by genio** [comment]
@jidanni If you pass an uninitialized variable to ```encode_punycode``` then there's nothing to encode and you get that error.

What behavior are you expecting from such an attempt?

**Comment by jidanni** [comment]
I did not pass an uninitialized variable.
Are there any examples of correct input and the resultant correct output that the user can use to verify that the program is operating properly? Could you please put some on the man page. You can even add uri_encode or uri_decode extra steps if you are worried that the man page will contain non-ASCII.

**Comment by genio** [comment]
The function ```encode_punycode``` takes a string. If you pass it an undefined value or nothing at all, it results in that error which is on the first line of the function. That function calls split on what it assumes is a string. Non-existent inputs will fail at that point.

```bash
$ perl -MURI::_punycode=encode_punycode -E 'say encode_punycode()'
Use of uninitialized value $input in split at /home/cwhitener/.perlbrew/libs/perl-5.26.1@normal/lib/perl5/URI/_punycode.pm line 96.

$ perl -MURI::_punycode=encode_punycode -E 'say encode_punycode(undef)'
Use of uninitialized value $input in split at /home/cwhitener/.perlbrew/libs/perl-5.26.1@normal/lib/perl5/URI/_punycode.pm line 96.

$ perl -MURI::_punycode=encode_punycode -E 'say encode_punycode("")'

$
```

Can you show us an example call to that function that fails for you?

**Comment by jidanni** [comment]
Yes, I can verify the above behaviour. So far so good. Now can you please give examples of typical usage on real strings.

**Comment by genio** [comment]
Here it is with URI::_punycode and Mojo::Util as well.

```bash
$ perl -MURI::_punycode=decode_punycode,encode_punycode -E 'say encode_punycode("http://☃.net")'
http://.net-iba6y10b
$ perl -MMojo::Util=punycode_encode -E 'say punycode_encode("http://☃.net")'
http://.net-iba6y10b
```

**Comment by karenetheridge** [comment]
@jidanni can you provide an example of code where you got this warning message?

**Comment by jidanni** [comment]
Ah, it turns out indeed I was giving it uninitailized variables just
like you said. That is due to me just running the SYNOPSIS.
Please make the SYNOPSIS runnable, like e.g., URI::QueryParam's.

**Comment by genio** [comment]
@jidanni I've taken a stab at updating the documentation to make things hopefully a bit clearer for anyone in the future.

Once the review process takes place, if these changes are accepted, the next release of the URI distribution should make the usage of URI::_punycode easier to see at a glance.
