### ISSUE TITLE
URI.pm code hangs forever

### ISSUE THREAD

**Issue by djugessur** [libwww-perl/URI#62]
Hi,

I ran into a very strange issue which I could only reproduce on certain VMs. We use URI::Find to find links in emails and one specific email was causing URI::Find to hang. I have attached a patch. Basically line 136 of URI.pm:

eval "require $ic";

would not return when the value of $ic was URI::com2

I changed it to:

eval {require $ic};

and that returns fine.

Thanks

I also (maybe mistakenly) created an issue in URI::Find as that was what I was using.   https://github.com/schwern/URI-Find/issues/20#issue-407911926

[URI.pm.patch.txt](https://github.com/libwww-perl/URI/files/2846291/URI.pm.patch.txt)

**Comment by oalders** [comment]
Thanks @djugessur!

Patch looks to be:

```perl
--- URI.pm.orig	2016-01-07 20:15:54.000000000 -0500
+++ URI.pm	2019-02-07 15:48:03.965581700 -0500
@@ -133,7 +133,7 @@
         if (not exists $require_attempted{$ic}) {
             # Try to load it
             my $_old_error = $@;
-            eval "require $ic";
+            eval {require $ic};  
             die $@ if $@ && $@ !~ /Can\'t locate.*in \@INC/;
             $@ = $_old_error;
         }
```

**Comment by oalders** [comment]
@djugessur do you have any code to reproduce the issue?

**Comment by oalders** [comment]
@djugessur do you see the same issue if your replace that line with:

```perl
use Module::Runtime qw( require_module );
require_module( $ic );
```

**Comment by djugessur** [comment]
Yes, it still freezes with require_module code change.

As for repro, the value for $ic that causes this is URI::com2

Please note that it only happens on the VMs I'm trying out ... haven't managed to repro on a physical machine ... I'm completely mystified by that.

**Comment by karenetheridge** [comment]
`eval {require $ic};` is not the same thing as `eval "require $ic"` and it will always fail, so it is not a good replacement.

**Comment by karenetheridge** [comment]
URI::com2 doesn't exist on cpan. Where did you get it from?

**Comment by djugessur** [comment]
It was extracted from a text MIME part (utf-8) in an email in which I was trying to find URLS.

**Comment by djugessur** [comment]
[URIHangBug.zip](https://github.com/libwww-perl/URI/files/2846497/URIHangBug.zip)

I have uploaded a repro sample along with the email

**Comment by karenetheridge** [comment]
@djugessur URI::com2 is not part of this distribution or on cpan. We have no idea what code is being run in there.

**Comment by djugessur** [comment]
@karenetheridge understood.  So the issue could be why $scheme is being passed the value com2 in the implementor function.  

Could you explain the difference between eval "require $ic" and eval {require $ic} to a perl noob?  I thought it was just a compile once thing.

**Comment by oalders** [comment]
```shell
	eval 'require URI::com2' called at /Users/olafalders/.plenv/versions/5.26.1/lib/perl5/site_perl/5.26.1/URI.pm line 135
	URI::implementor("com2") called at /Users/olafalders/.plenv/versions/5.26.1/lib/perl5/site_perl/5.26.1/URI.pm line 59
	URI::new("URI", "com2:45") called at /Users/olafalders/.plenv/versions/5.26.1/lib/perl5/site_perl/5.26.1/URI/Find.pm line 521
	eval {...} called at /Users/olafalders/.plenv/versions/5.26.1/lib/perl5/site_perl/5.26.1/URI/Find.pm line 520
	URI::Find::_is_uri(URI::Find=HASH(0x7f8d6502fd20), SCALAR(0x7f8d66561650)) called at /Users/olafalders/.plenv/versions/5.26.1/lib/perl5/site_perl/5.26.1/URI/Find.pm line 200
	URI::Find::_uri_filter(URI::Find=HASH(0x7f8d6502fd20), undef) called at /Users/olafalders/.plenv/versions/5.26.1/lib/perl5/site_perl/5.26.1/URI/Find.pm line 177
	URI::Find::find(URI::Find=HASH(0x7f8d6502fd20), SCALAR(0x7f8d6502fa80)) called at repro.pl line 50
	main::ExtractURLs("B0017384045.MSG") called at repro.pl line 58
```

**Comment by karenetheridge** [comment]
See the discussion of barewords at https://perldoc.pl/functions/require.

**Comment by oalders** [comment]
It looks like `URI::Find` thinks that `com2:45` is an URL.

**Comment by djugessur** [comment]
@oalders, agreed.  But why the freeze on VMs when doing the eval? (all were windows vms, one win2k8, one win2k12)?

**Comment by oalders** [comment]
@djugessur that I cannot answer.  I haven't been at a Windows machine in a lot of years.  That might be a question for StackOverflow if we don't get it sorted here.  

@mithaldu, you're a Windows user, correct?  Any ideas about the above?

**Comment by djugessur** [comment]
I can repro it with just the following on the vms ... looks like it might be a bug in require itself.  Thanks for the help @karenetheridge and @oalders 

..\bin\perl -Mstrict -e "eval \"require URI::com2\""

**Comment by djugessur** [comment]
Figured it out!  Well figured out why it's freezing on windows boxes.  com2 is the serial port which was open on the vm.  Somehow "require URI::com2" is opening the com port and listening.  Closing the com port in device manager stops the freeze so for sure it is related.  Madness.

**Comment by karenetheridge** [comment]
I would check the value of `@INC` on those machines (see `perl -V`), and check that all of those paths actually exist on real filesystems. There might be a path that maps to a slow or nonexistent virtual filesystem.

**Comment by djugessur** [comment]
@karenetheridge, I realize that you have closed the issue but I was wondering if the following attached patch is a better solution than the earlier patch I had added:

[URI.pm.patch.txt](https://github.com/libwww-perl/URI/files/2851738/URI.pm.patch.txt)

Now it should compile every time but will no longer expand to OS filesystem.

Also, existing code is prone to injection as I have shown in this bug ... if attached patch is no good, is there an alternative to "require" that can be used?

**Comment by karenetheridge** [comment]
`require "Foo::Bar"` would look for a file named `Foo::Bar` in `@INC`, which is not what we want. Quotes should be used iff the argument is a filename, not a module.

What is the mechanism by which attempting to load a file named `URI::com2` is resulting in opening a serial port? That seems mighty strange.  Is it possible to `strace` this?

**Comment by djugessur** [comment]
This is in windows so strace is not an option.  I'll check for an alternative way but my guess is that the "require" function is touching the file and as there are reserved words in windows which are not allowed for filenames e.g. com2, they should be filtered in windows for the require function.  Accessing them can results in accessing the device itself.  

Easily reproducible on any windows box with a com port open by: 

..\bin\perl -Mstrict -e "eval \"require URI::com2\""

From https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#win32-file-namespaces:

Do not use the following reserved names for the name of a file:

CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.

**Comment by djugessur** [comment]
![perlcom](https://user-images.githubusercontent.com/25909327/52583883-a1bd6d80-2dfe-11e9-8999-3a7364324e4d.png)

Attached image is windows dmp of perl when executing:

..\bin\perl -Mstrict -e "eval "require URI::com2""

You can see that it is actually reading from a handle which I'm assuming is to the com port

**Comment by djugessur** [comment]
![perlcom2](https://user-images.githubusercontent.com/25909327/52588612-df27f800-2e0a-11e9-860f-311e979a8cfc.png)

Above show perl process and files it has access to, see \Device\Serial0 which is the com port it currently has opened.

**Comment by karenetheridge** [comment]
windows 💩 💩
