### ISSUE TITLE
installed escape_char() diff from original

### ISSUE THREAD

**Issue by hirafoo** [libwww-perl/URI#73]
original URI::Escape#escape_char is
https://metacpan.org/source/OALDERS/URI-1.76/lib/URI/Escape.pm#L207
```
sub escape_char {
    # Old versions of utf8::is_utf8() didn't properly handle magical vars (e.g. $1).
    # The following forces a fetch to occur beforehand.
    my $dummy = substr($_[0], 0, 0);
 
    if (utf8::is_utf8($_[0])) {
        my $s = shift;
        utf8::encode($s);
        unshift(@_, $s);
    }
 
    return join '', @URI::Escape::escapes{split //, $_[0]};
}
```

but I do install with carton, the function is
```
sub escape_char {
    return join '', @URI::Escape::escapes{$_[0] =~ /(\C)/g};
}
```

and this function occur error `\C no longer supported in regex; marked by <-- HERE in m/(\ <-- HERE C)/`

why ?

I install with careton, and cpanfile is
```
requires 'URI::Escape'  => '==3.31';
```

and installed version is 3.31. and I using perl 5.32.0.
```
% perl -e 'warn $]'
5.032000 at -e line 1.
```

could you help me ?

**Comment by hirafoo** [comment]
diff from original one is below.

```
% diff /path/to/installed/URI/Escape.pm /path/to/original/Escape.pm
1a2
>
2a4
> use warnings;
138,139c140
< require Exporter;
< our @ISA = qw(Exporter);
---
> use Exporter 5.57 'import';
182a184
>     return undef unless defined $text;
203a206
> # XXX FIXME escape_char is buggy as it assigns meaning to the string's storage format.
205c208,218
<     return join '', @URI::Escape::escapes{$_[0] =~ /(\C)/g};
---
>     # Old versions of utf8::is_utf8() didn't properly handle magical vars (e.g. $1).
>     # The following forces a fetch to occur beforehand.
>     my $dummy = substr($_[0], 0, 0);
>
>     if (utf8::is_utf8($_[0])) {
>         my $s = shift;
>         utf8::encode($s);
>         unshift(@_, $s);
>     }
>
>     return join '', @URI::Escape::escapes{split //, $_[0]};
```

**Comment by oalders** [comment]
Oh, wow. The version numbering for this distribution is a bit messed up:

```
lib/URI/Escape.pm:144:our $VERSION = "3.31";
lib/URI/Heuristic.pm:94:our $VERSION = "4.20";
lib/URI/URL.pm:8:our $VERSION = "5.04";
lib/URI/WithBase.pm:9:our $VERSION = "2.20";
lib/URI/file.pm:7:our $VERSION = "4.21";
```

Those versions have been remaining static over the various releases lately, I think, so there are a number of different releases which a `URI::Escape` at 3.31

@hirafoo can you change your `cpanfile` to something like:

`requires 'URI'  => '==1.76';`

That should pull in the latest `URI::Escape`, assuming that's what you want.

**Comment by oalders** [comment]
Not sure if this will work in tandem with an older `cpanfile.snapshot`, so you may need to update your snapshot as well.

**Comment by hirafoo** [comment]
@oalders 
thank you fast reply.
I was wrong and got it now.
I have to specify version for URI, not URI::Escape...
I changed my cpanfile as you told and looks work well.

**Comment by oalders** [comment]
@hirafoo that's great! I'm going to re-open this issue as it has uncovered the fact that our version numbers are not consistent and that's something we'd like to fix. :)
