### ISSUE TITLE
liburi-perl: URI nntps support

### ISSUE THREAD

**Issue by gregoa** [libwww-perl/URI#82]
We have the following bug reported to the Debian package of URI, c.f.
https://bugs.debian.org/983419

It doesn't seem to be a bug in the packaging, so you may want to take
a look. Thanks!

------8<-----------8<-----------8<-----------8<-----------8<-----

```
Package: liburi-perl
Version: 1.76-1
Severity: wishlist
Tags: upstream

While URI::snews exists for NNTP over TLS, "nntps" is the IANA-registered name:

https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=nntps

Also, "nntps" (not "snews") is present in /etc/services shipped with Debian.

Thanks in advance for forwarding to upstream to me.


```
------8<-----------8<-----------8<-----------8<-----------8<-----

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by oalders** [comment]
Thanks @gregoa!

Let's see. Looks like the inspiration was [draft-gilman-news-url-01](https://tools.ietf.org/html/draft-gilman-news-url-01) and the commit is ee593ea8 from 1998-09-11

In `/etc/services` on my Mac I also see:

```
nntps           563/udp     # nntp protocol over TLS/SSL (was snntp)
nntps           563/tcp     # nntp protocol over TLS/SSL (was snntp)
```

So, it looks like we have something to fix here.

**Comment by karenetheridge** [comment]
What is the problem being described here? Is it that URI::nntp::default_port is 119 but it ought to be 563? or is something wrong with URI::snews?

**Comment by gregoa** [comment]
On Fri, 26 Feb 2021 11:40:17 -0800, Karen Etheridge wrote:

> What is the problem being described here? Is it that
> URI::nntp::default_port is 119 but it ought to be 563? or is
> something wrong with URI::snews?

In my understanding, the problem _is_ URI::snews :)

"NNTP over TLS" is officially called "nntps" (and not "snews", as in
some old draft); so I suppose there should be some s/snews/nntps/g
(module backcompat and documentation etc.) in the distribution.

Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-   NP: Mark Knopfler: Wanderlust

**Comment by karenetheridge** [comment]
Okay, we can add a URI::nntps module fairly easily...

**Comment by gregoa** [comment]
Thank you!

I guess you're aware but just for completeness: I think this needs some more changes in documentation and comments, cf.
```
% egrep -r '(snews|gilman)' lib
lib/URI/nntp.pm:package URI::nntp;  # draft-gilman-news-url-01
lib/URI/snews.pm:package URI::snews;  # draft-gilman-news-url-01
lib/URI/news.pm:package URI::news;  # draft-gilman-news-url-01
lib/URI/news.pm:#   scheme       =  "news" | "snews" | "nntp"
lib/URI.pm:The I<news>, I<nntp> and I<snews> URI schemes are specified in
lib/URI.pm:<draft-gilman-news-url-01> and will hopefully be available as an RFC
lib/URI.pm:=item B<snews>:
```

**Comment by karenetheridge** [comment]
Agreed - I pushed a few more commits.
