### ISSUE TITLE
t/urn-isbn.t may fail

### ISSUE THREAD

**Issue by eserte** [libwww-perl/URI#83]
Seen on some of my smokers:
```
Use of uninitialized value in string eq at t/urn-isbn.t line 19.
Use of uninitialized value in numeric eq (==) at t/urn-isbn.t line 22.
Use of uninitialized value in numeric eq (==) at t/urn-isbn.t line 25.
Use of uninitialized value in string eq at t/urn-isbn.t line 28.
Use of uninitialized value in string eq at t/urn-isbn.t line 34.
Use of uninitialized value in string eq at t/urn-isbn.t line 40.
t/urn-isbn.t .............. 
Failed 7/13 subtests 
```
It's possible that this is caused by some version of Business::ISBN; especially if the latest version is installed, then this does not seem to happen.

**Comment by oalders** [comment]
Any thoughts on what to do here, @briandfoy?

**Comment by briandfoy** [comment]
Did I screw up something?

**Comment by karenetheridge** [comment]
> It's possible that this is caused by some version of Business::ISBN; especially if the latest version is installed, then this does not seem to happen.

When enough results are in, we should be able to do some statistical analysis to see what version(s) are affected, confirm with a bisect, and then set the minimum version to be high enough to not see this problem.

**Comment by briandfoy** [comment]
May be related: https://github.com/briandfoy/business-isbn-data/issues/7

There were a few versions (3.003, 3.004 at least) where I messed up the data structure by having a duplicate hash key. This meant that most publisher codes disappeared. @eserte has the stats at https://github.com/briandfoy/business-isbn-data/issues/8 . 

I had previously assumed that CPAN Testers started fresh for each test, so I was initially confused when I was changing things without improving the situation.

I recommend at least Business::ISBN 3.005 (which fixes the group issue) and whatever the latest version of Business::ISBN::Data is.

**Comment by eserte** [comment]
> When enough results are in, we should be able to do some statistical analysis to see what version(s) are affected, confirm with a bisect, and then set the minimum version to be high enough to not see this problem.

@karenetheridge: Unfortunately Business:ISBN neither appears in the standard prereqs block of a Test::Reporter block nor it's listed in the t/00-report-prereqs.t output, so the standard statistical analysis approach does not work here.

**Comment by karenetheridge** [comment]
That's odd, it should be showing up in the report: https://metacpan.org/source/OALDERS/URI-5.09/t%2F00-report-prereqs.dd#L12

..but I see that it isn't. I'll investigate.
