### ISSUE TITLE
mailto:user+detail@domain is not parsed correctly

### ISSUE THREAD

**Issue by jpcornet** [libwww-perl/URI#89]
A "+" in a mailto: URL should not be changed, unlike in other schemes. See the explanation in https://datatracker.ietf.org/doc/html/rfc6068#section-5

Example that currently fails:

```perl
$uri = URI->new('mailto:user+detail@example.com');
is($uri->to, 'user+detail@example.com', "mailto parsed correctly");
```

**Comment by oalders** [comment]
Looks like *may* be changed to `%2B` or left as is? Either way the current behaviour needs a tweak. a pull request would be great.

```
perl -MURI -E "say URI->new('mailto:user+detail@example.com')->to"
user detail@example.com
```
